#!/bin/bash

# L'utilisation de ce script est documentée à cette adresse :
# https://github.com/dorian-marchal/spawnkill/blob/master/documentation/LocalUserscriptDev.md

CURRENT_DIR="$( cd "$( dirname "$0" )" && pwd )"
. "${CURRENT_DIR}/local-dev-config.sh"

# On supprime tout ce qui se trouve dans le répertoire
if [ ! -z "${gm_script_path}" ]; then

    # Pour une question de sécurité, on ne supprime que les types de fichiers suivants
    for ext in {".js",".png",".jpg",".gif",".jpeg",".ogg",".mp3"}; do
        rm -f ${gm_script_path}*$ext
    done

    # On importe le script principal
    ln -sv "${dev_script_path}${main_script_file}" "$gm_script_path"

    # Et on importe les scripts et les ressources nécessaires au script
    regex="^\/\/ @(require[[:space:]]*|resource[[:space:]]+[^[:space:]]+[[:space:]]+)([^[:space:]\?]*)(\?.*)?$"

    while read line; do

        if [[ $line =~ $regex ]]; then
            file="${BASH_REMATCH[2]}"
            echo "Copie du fichier $file."
            ln -sv "${dev_script_path}${file}" "$gm_script_path"
        fi

    done < ${dev_script_path}${main_script_file}
fi